FROM python:3.13-slim

ENV PYTHONUNBUFFERED=1
WORKDIR /app/cron

# Install cron package
COPY app/cron/ .
RUN pip install --no-cache-dir -e .

# Install tooling for tests, linting, formatting, etc.
COPY local/requirements.dev.txt /tmp/requirements.dev.txt
RUN pip install --no-cache-dir -r /tmp/requirements.dev.txt

CMD ["tail", "-f", "/dev/null"]
