services:
  lab:
    build:
      context: ..
      dockerfile: local/Dockerfile.lab
    container_name: sparrow_cam_lab
    volumes:
      - ../app/lab:/app/lab
      - ../app/processor:/app/processor
      - ../.storage/lab:/.storage
      - ../infra/ansible/.secrets/ssh_key:/secrets/ssh_key
      - ../infra/ansible/group_vars/all.yml:/secrets/all.yml
