FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y \
    libsm6 \
    libxext6 \
    libgl1 \
    libglib2.0-0 \
    gcc \
    g++ \
    git \
    libpython3-dev \
    libusb-1.0-0

RUN pip install opencv-python-headless flask ultralytics

WORKDIR /app
COPY processor.py .

ENV PYTHONUNBUFFERED=1

CMD ["python", "processor.py"]
