FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y \
    libsm6 \
    libxext6 \
    libgl1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install opencv-python-headless flask

WORKDIR /app
COPY processor.py .

ENV PYTHONUNBUFFERED=1

CMD ["python", "processor.py"]
