---
- name: Setup Users and Groups
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      include_tasks: tasks/apt_update.yml

    - name: Create sparrow_cam group
      group:
        name: sparrow_cam
        state: present

    - name: Add www-data to sparrow_cam group
      user:
        name: www-data
        groups: sparrow_cam
        append: yes

    - name: Create sparrow_cam_app user
      user:
        name: sparrow_cam_app
        shell: /bin/bash
        home: /opt/sparrow_cam_app
        create_home: yes
        groups: sparrow_cam
        append: yes
        system: no
        state: present

    - name: Create temp directory for sparrow_cam_app
      file:
        path: /opt/sparrow_cam_app/tmp
        state: directory
        owner: sparrow_cam_app
        group: sparrow_cam_app
        mode: '0700'

    - name: Create apps directory for sparrow_cam_app
      file:
        path: /opt/sparrow_cam_app/apps
        state: directory
        owner: sparrow_cam_app
        group: sparrow_cam_app
        mode: '0755'

    - name: Install build dependencies
      apt:
        name:
          - build-essential
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - curl
          - git
          - libncursesw5-dev
          - xz-utils
          - libffi-dev
          - liblzma-dev
          - libgl1
          - libglib2.0-0
          - acl
        state: present

    - name: Add sparrow_cam_infra to sparrow_cam group
      user:
        name: sparrow_cam_infra
        groups: sparrow_cam
        append: yes

    - name: Enable passwordless sudo for sparrow_cam_infra
      copy:
        content: "sparrow_cam_infra ALL=(ALL) NOPASSWD:ALL\n"
        dest: /etc/sudoers.d/sparrow_cam_infra
        owner: root
        group: root
        mode: '0440'
        validate: /usr/sbin/visudo -cf %s
