name: Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  processor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DOCKER_BUILDKIT: "1"
      COMPOSE_DOCKER_CLI_BUILD: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make -C local build

      - name: Check
        run: make -C local processor-check

      - name: Test
        run: make -C local processor-test

      - name: Cleanup
        if: always()
        run: docker compose -f local/docker-compose.yml down --volumes --remove-orphans

  lab:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DOCKER_BUILDKIT: "1"
      COMPOSE_DOCKER_CLI_BUILD: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make -C local build lab-build

      - name: Check
        run: make -C local lab-check

      - name: Test
        run: make -C local lab-test

      - name: Cleanup
        if: always()
        run: docker compose -f local/docker-compose.lab.yml down --volumes --remove-orphans

  archive-api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DOCKER_BUILDKIT: "1"
      COMPOSE_DOCKER_CLI_BUILD: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make -C local archive-api-build

      - name: Check
        run: make -C local archive-api-check

      - name: Test
        run: make -C local archive-api-test

      - name: Cleanup
        if: always()
        run: docker compose -f local/docker-compose.yml down --volumes --remove-orphans

  cron:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DOCKER_BUILDKIT: "1"
      COMPOSE_DOCKER_CLI_BUILD: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make -C local cron-build

      - name: Check
        run: make -C local cron-check

      - name: Test
        run: make -C local cron-test

      - name: Cleanup
        if: always()
        run: docker compose -f local/docker-compose.yml down --volumes --remove-orphans
